name: release-notes
description: |
  Retrieves release-notes following conventions from Gardener-Project.

runs:
  using: composite
  steps:
    - name: install-gardener-gha-libs
      uses: ./.github/actions/install-gardener-gha-libs
    - name: collect-release-notes
      shell: bash
      run: |
        echo "test.."
        set -x
        which python3
        which python
        python3 -c "import release_notes"
